matrix:
  include:
  - language: python
    python:
    - '2.7'
    before_install:
    - sudo apt-get update -qq
    - pip install . --process-dependency-links
    - pip install -r python/dev-requirements.txt
    script:
    - nosetests python/
    - flake8 python
    - ga4gh_wes_client
  - language: java
    jdk: oraclejdk8
    before_install:
    - chmod +x gradlew
    script:
    - rm -rf docs/asciidoc/swagger2markup
    - "./gradlew asciidoctor"
    after_success:
    - cp docs/html5/index.html docs/
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      on:
        all_branches: true
